order/order_item/category models
ShahdElmahallawy/ecommerce pull request #5
Opened 2024-08-14 09:00 UTC by ahmadsameh8

2024-08-14 09:19 UTC, ShahdElmahallawy commented on api/models/category.py
> +    featred_product = models.ForeignKey("Product", on_delete=models.CASCADE, related_name='category')
Remove the foreign key. It should be in the product.

2024-08-19 12:36 UTC, AmrElkfrawy requested changes

2024-08-19 12:36 UTC, AmrElkfrawy commented on ecommerce/settings.py
> +    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
We don’t need all endpoints to be protected by default add permissions whenever it's needed, this line can be removed.

2024-08-19 12:36 UTC, AmrElkfrawy commented on ecommerce/settings.py
> +    "rest_framework.authtoken",
We used JWT for authentication instead of token based authentication,  this line can be removed.

2024-08-19 12:36 UTC, AmrElkfrawy commented on api/views/category.py
- List and Detail view don't need authentication permissions.
- Update, Create, and Delete should require admin permissions so normal users can't use them

2024-08-19 12:36 UTC, AmrElkfrawy commented on api/urls.py
Following this pattern in urls is much cleaner
https://github.com/HackSoftware/Django-Styleguide?tab=readme-ov-file#urls

2024-08-19 12:36 UTC, AmrElkfrawy commented on api/serializers/product_serializer.py
> +        fields = "__all__"
Not recommended to use all

2024-08-19 12:36 UTC, AmrElkfrawy commented on api/serializers/order_item.py
> +        fields = ["id", "product", "quantity", "unit_price"]
We can create simple product serializer for product to show more details about that products instead of only ID

2024-08-19 12:36 UTC, AmrElkfrawy commented on api/models/category.py
> +        Product, on_delete=models.CASCADE, related_name="category"
The related name will conflict with category filed in product, should be changed

2024-08-25 09:39 UTC, merged